name: {{ cookiecutter.conda_environment_name }}

channels:
  - esri
  - conda-forge

dependencies:
  - esri::arcgis
  - cookiecutter
  - jupyterlab
  - nodejs
  - dask
  - fiona
  - pygeos
  - geopandas
  - pandas
  - git
  - sphinx
  - pip
  - conda-forge::pyarrow
  - python=3.7
  - python-dotenv
  - r-tidyverse
  - r-sf
  - r-tmap
  - pip:
#    - -e ../../packages/emma  # requires
#    - -e ../../packages/rputils
#    - -e ../../packages/algi
#    - -e ../../packages/rpio
    - esridump
    - azure-storage-blob
    - boto3