name: {{ cookiecutter.conda_environment_name }}

channels:
  - esri
  - conda-forge

dependencies:
  - esri:arcpy
  - esri::arcgis
  - cookiecutter
  - jupyterlab
  - nodejs
  - dask
  - pandas
  - git
  - sphinx
  - pip
  - conda-forge::pyarrow
  - python=3.7
  - python-dotenv
  - r-tidyverse
  - r-sf
  - r-tmap
  - esri::r-arcgisbinding
  - pip:
    - esridump
    - azure-storage-blob
    - boto3