name: {{ cookiecutter.conda_arc_environment_name }}

channels:
  - esri
  - conda-forge

dependencies:
  - esri::arcgis
  - esri::arcpy
  - pandas
  - dask
  - h3-py
  - jupyterlab
  - nodejs
  - mkdocs
  - munch
  - momepy
  - pip
  - pytest
  - esri::mkl
  - mkl_fft
  - mkl-service=2.3
  - mkl_random
  - python=3.7
  - python-dotenv
  - pyyaml
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - tabulate
  - tqdm
  - xlrd
  - git     # required for package switcher
  - GitPython # required for package switcher
  - pip:
#    - ../../packages/esri_tools  # future package to be used with ESRI arcpy tools
    - esridump
    - simpledbf
    - azure-storage-blob
    - boto3