name: test

channels:
  - conda-forge
  - anaconda

dependencies:
  - appdirs
  - pip
  - pip:
    - -e ../../packages/rputils
#    - -e ../../packages/algi
#    - -e ../../packages/emma
#    - -e ../../packages/gary
#    - -e ../../packages/biff
#    - -e ../../packages/roxy
#    - -e ../../packages/sophia


rp_dependencies:
  - appdirs
  - pip
  - pip:
      - -e ../../rputils
#      - -e ../algi
#      - -e ../emma
#      - -e ../gary
#      - -e ../biff
#      - -e ../roxy
#      - -e ../sophia